"""
routes/monte_carlo.py
Monte Carlo Simulation API endpoints.
"""

import os
from flask import Blueprint, jsonify, send_file, request
from flask_jwt_extended import jwt_required
from backend.ml.monte_carlo import run_all_simulations, load_cached_results, GRAPHS_DIR
from backend.middleware.auth_middleware import admin_required

mc_bp = Blueprint("monte_carlo", __name__, url_prefix="/api/monte-carlo")


@mc_bp.route("/run", methods=["POST"])
@admin_required
def run_simulation():
    """
    POST /api/monte-carlo/run
    Executes all four Monte Carlo simulations (10,000 runs each).
    Returns probability estimates for:
      - Delivery Delay
      - Inventory Stockout
      - Supplier Failure
      - Transportation Delay
    Also generates and saves distribution graph PNGs.
    """
    try:
        results = run_all_simulations()
        return jsonify(results), 200
    except Exception as e:
        return jsonify({"error": f"Monte Carlo simulation failed: {str(e)}"}), 500


@mc_bp.route("/results", methods=["GET"])
@jwt_required()
def get_cached_results():
    """
    GET /api/monte-carlo/results
    Returns the most recently cached Monte Carlo results (if any).
    Use POST /api/monte-carlo/run to generate fresh results first.
    """
    results = load_cached_results()
    if not results:
        return jsonify({
            "message": "No simulation results found. Run POST /api/monte-carlo/run first."
        }), 404
    return jsonify(results), 200


@mc_bp.route("/graph/<filename>", methods=["GET"])
def get_graph(filename: str):
    """
    GET /api/monte-carlo/graph/<filename>
    Serves a Monte Carlo probability distribution graph PNG.
    Available filenames (generated by POST /run):
      - delivery_delay.png
      - inventory_stockout.png
      - supplier_failure.png
      - transportation_delay.png
    No authentication required (public graph serving for frontend charts).
    """
    # Sanitize filename to prevent directory traversal
    safe_name = os.path.basename(filename)
    path = os.path.join(GRAPHS_DIR, safe_name)

    if not os.path.exists(path):
        return jsonify({"error": "Graph not found. Run POST /api/monte-carlo/run first."}), 404

    return send_file(path, mimetype="image/png")
